"""Initial schema

Revision ID: 4395dcc753e4
Revises: 
Create Date: 2026-05-30 00:47:37.900391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4395dcc753e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_alerts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('check_in_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('caregiver_phone_number', sa.String(length=30), nullable=True),
    sa.Column('caregiver_call_sid', sa.String(length=80), nullable=True),
    sa.Column('caregiver_call_status', sa.String(length=40), nullable=True),
    sa.Column('caregiver_call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=False),
    sa.Column('delivery_status', sa.String(length=80), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregiver_alerts_caregiver_call_sid'), 'caregiver_alerts', ['caregiver_call_sid'], unique=False)
    op.create_index(op.f('ix_caregiver_alerts_check_in_id'), 'caregiver_alerts', ['check_in_id'], unique=False)
    op.create_index(op.f('ix_caregiver_alerts_id'), 'caregiver_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_caregiver_alerts_risk_level'), 'caregiver_alerts', ['risk_level'], unique=False)
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('senior_phone_number', sa.String(length=30), nullable=True),
    sa.Column('twilio_phone_number', sa.String(length=30), nullable=True),
    sa.Column('senior_call_sid', sa.String(length=80), nullable=True),
    sa.Column('senior_call_status', sa.String(length=40), nullable=True),
    sa.Column('senior_call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('speech_confidence', sa.String(length=40), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reported_symptoms_json', sa.Text(), nullable=False),
    sa.Column('red_flags_json', sa.Text(), nullable=False),
    sa.Column('orientation_concern', sa.Boolean(), nullable=False),
    sa.Column('escalation_needed', sa.Boolean(), nullable=False),
    sa.Column('caregiver_summary', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('confidence_notes', sa.Text(), nullable=True),
    sa.Column('analyzer', sa.String(length=80), nullable=True),
    sa.Column('raw_analysis_json', sa.Text(), nullable=False),
    sa.Column('caregiver_alert_required', sa.Boolean(), nullable=False),
    sa.Column('caregiver_alert_sent', sa.Boolean(), nullable=False),
    sa.Column('caregiver_alert_type', sa.String(length=50), nullable=True),
    sa.Column('caregiver_alert_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_id'), 'check_ins', ['id'], unique=False)
    op.create_index(op.f('ix_check_ins_risk_level'), 'check_ins', ['risk_level'], unique=False)
    op.create_index(op.f('ix_check_ins_senior_call_sid'), 'check_ins', ['senior_call_sid'], unique=False)
    op.create_table('heat_risk_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('heat_risk_value', sa.Integer(), nullable=False),
    sa.Column('heat_risk_label', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_response_json', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heat_risk_observations_heat_risk_value'), 'heat_risk_observations', ['heat_risk_value'], unique=False)
    op.create_index(op.f('ix_heat_risk_observations_id'), 'heat_risk_observations', ['id'], unique=False)
    op.create_index(op.f('ix_heat_risk_observations_senior_id'), 'heat_risk_observations', ['senior_id'], unique=False)
    op.create_table('heat_triggered_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.String(length=20), nullable=False),
    sa.Column('heat_risk_value', sa.Integer(), nullable=False),
    sa.Column('heat_risk_label', sa.String(length=40), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('senior_call_sid', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heat_triggered_calls_id'), 'heat_triggered_calls', ['id'], unique=False)
    op.create_index(op.f('ix_heat_triggered_calls_local_date'), 'heat_triggered_calls', ['local_date'], unique=False)
    op.create_index(op.f('ix_heat_triggered_calls_senior_call_sid'), 'heat_triggered_calls', ['senior_call_sid'], unique=False)
    op.create_index(op.f('ix_heat_triggered_calls_senior_id'), 'heat_triggered_calls', ['senior_id'], unique=False)
    op.create_table('senior_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('preferred_language', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_senior_profiles_id'), 'senior_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_senior_profiles_phone_number'), 'senior_profiles', ['phone_number'], unique=False)
    op.create_table('caregiver_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('relationship', sa.String(length=80), nullable=True),
    sa.Column('alert_priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregiver_profiles_id'), 'caregiver_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_caregiver_profiles_phone_number'), 'caregiver_profiles', ['phone_number'], unique=False)
    op.create_index(op.f('ix_caregiver_profiles_senior_id'), 'caregiver_profiles', ['senior_id'], unique=False)
    op.create_table('check_in_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('time_of_day', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('days_of_week_json', sa.Text(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_schedules_id'), 'check_in_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_check_in_schedules_senior_id'), 'check_in_schedules', ['senior_id'], unique=False)
    op.create_table('escalation_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('living_situation', sa.String(length=60), nullable=False),
    sa.Column('support_mode', sa.String(length=60), nullable=False),
    sa.Column('allow_operator_review', sa.Boolean(), nullable=False),
    sa.Column('allow_wellness_check', sa.Boolean(), nullable=False),
    sa.Column('allow_emergency_escalation', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('senior_id', name='uq_escalation_plans_senior_id')
    )
    op.create_index(op.f('ix_escalation_plans_id'), 'escalation_plans', ['id'], unique=False)
    op.create_index(op.f('ix_escalation_plans_senior_id'), 'escalation_plans', ['senior_id'], unique=False)
    op.create_table('senior_demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=40), nullable=True),
    sa.Column('pronouns', sa.String(length=40), nullable=True),
    sa.Column('primary_language', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('senior_id', name='uq_senior_demographics_senior_id')
    )
    op.create_index(op.f('ix_senior_demographics_id'), 'senior_demographics', ['id'], unique=False)
    op.create_index(op.f('ix_senior_demographics_senior_id'), 'senior_demographics', ['senior_id'], unique=False)
    op.create_table('senior_heat_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('trigger_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('senior_id', name='uq_senior_heat_settings_senior_id')
    )
    op.create_index(op.f('ix_senior_heat_settings_id'), 'senior_heat_settings', ['id'], unique=False)
    op.create_index(op.f('ix_senior_heat_settings_senior_id'), 'senior_heat_settings', ['senior_id'], unique=False)
    op.create_table('support_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('relationship', sa.String(length=80), nullable=True),
    sa.Column('contact_type', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('can_receive_alerts', sa.Boolean(), nullable=False),
    sa.Column('is_emergency_contact', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_contacts_id'), 'support_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_support_contacts_phone_number'), 'support_contacts', ['phone_number'], unique=False)
    op.create_index(op.f('ix_support_contacts_senior_id'), 'support_contacts', ['senior_id'], unique=False)
    op.create_table('voice_baseline_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('check_in_id', sa.Integer(), nullable=True),
    sa.Column('baseline_sample_id', sa.Integer(), nullable=True),
    sa.Column('senior_call_sid', sa.String(length=80), nullable=True),
    sa.Column('baseline_call_sid', sa.String(length=80), nullable=True),
    sa.Column('baseline_transcript', sa.Text(), nullable=True),
    sa.Column('current_transcript', sa.Text(), nullable=True),
    sa.Column('baseline_speech_confidence', sa.Float(), nullable=True),
    sa.Column('current_speech_confidence', sa.Float(), nullable=True),
    sa.Column('baseline_word_count', sa.Integer(), nullable=False),
    sa.Column('current_word_count', sa.Integer(), nullable=False),
    sa.Column('word_count_ratio', sa.Float(), nullable=True),
    sa.Column('confidence_delta', sa.Float(), nullable=True),
    sa.Column('confidence_drop_detected', sa.Boolean(), nullable=False),
    sa.Column('shorter_response_detected', sa.Boolean(), nullable=False),
    sa.Column('baseline_deviation_level', sa.String(length=20), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=False),
    sa.Column('raw_comparison_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_baseline_comparisons_baseline_call_sid'), 'voice_baseline_comparisons', ['baseline_call_sid'], unique=False)
    op.create_index(op.f('ix_voice_baseline_comparisons_baseline_sample_id'), 'voice_baseline_comparisons', ['baseline_sample_id'], unique=False)
    op.create_index(op.f('ix_voice_baseline_comparisons_check_in_id'), 'voice_baseline_comparisons', ['check_in_id'], unique=False)
    op.create_index(op.f('ix_voice_baseline_comparisons_id'), 'voice_baseline_comparisons', ['id'], unique=False)
    op.create_index(op.f('ix_voice_baseline_comparisons_senior_call_sid'), 'voice_baseline_comparisons', ['senior_call_sid'], unique=False)
    op.create_index(op.f('ix_voice_baseline_comparisons_senior_id'), 'voice_baseline_comparisons', ['senior_id'], unique=False)
    op.create_table('voice_baseline_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('senior_name', sa.String(length=120), nullable=True),
    sa.Column('senior_phone_number', sa.String(length=30), nullable=True),
    sa.Column('baseline_call_sid', sa.String(length=80), nullable=True),
    sa.Column('baseline_call_status', sa.String(length=40), nullable=True),
    sa.Column('baseline_call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('speech_confidence', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_baseline_samples_baseline_call_sid'), 'voice_baseline_samples', ['baseline_call_sid'], unique=False)
    op.create_index(op.f('ix_voice_baseline_samples_id'), 'voice_baseline_samples', ['id'], unique=False)
    op.create_index(op.f('ix_voice_baseline_samples_senior_id'), 'voice_baseline_samples', ['senior_id'], unique=False)
    op.create_table('check_in_call_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=True),
    sa.Column('senior_name', sa.String(length=120), nullable=False),
    sa.Column('senior_phone_number', sa.String(length=30), nullable=False),
    sa.Column('caregiver_name', sa.String(length=120), nullable=True),
    sa.Column('caregiver_phone_number', sa.String(length=30), nullable=True),
    sa.Column('senior_call_sid', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregiver_profiles.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_call_sessions_caregiver_id'), 'check_in_call_sessions', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_check_in_call_sessions_id'), 'check_in_call_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_check_in_call_sessions_senior_call_sid'), 'check_in_call_sessions', ['senior_call_sid'], unique=True)
    op.create_index(op.f('ix_check_in_call_sessions_senior_id'), 'check_in_call_sessions', ['senior_id'], unique=False)
    op.create_table('escalation_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('trigger_level', sa.String(length=40), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('target_contact_id', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['escalation_plans.id'], ),
    sa.ForeignKeyConstraint(['target_contact_id'], ['support_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_steps_id'), 'escalation_steps', ['id'], unique=False)
    op.create_index(op.f('ix_escalation_steps_plan_id'), 'escalation_steps', ['plan_id'], unique=False)
    op.create_index(op.f('ix_escalation_steps_target_contact_id'), 'escalation_steps', ['target_contact_id'], unique=False)
    op.create_table('operator_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('target_contact_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.ForeignKeyConstraint(['target_contact_id'], ['support_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_actions_action_type'), 'operator_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_operator_actions_id'), 'operator_actions', ['id'], unique=False)
    op.create_index(op.f('ix_operator_actions_senior_id'), 'operator_actions', ['senior_id'], unique=False)
    op.create_index(op.f('ix_operator_actions_status'), 'operator_actions', ['status'], unique=False)
    op.create_index(op.f('ix_operator_actions_target_contact_id'), 'operator_actions', ['target_contact_id'], unique=False)
    op.create_table('conversation_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('check_in_id', sa.Integer(), nullable=True),
    sa.Column('call_session_id', sa.Integer(), nullable=True),
    sa.Column('senior_call_sid', sa.String(length=80), nullable=True),
    sa.Column('safety_risk_level', sa.String(length=30), nullable=False),
    sa.Column('safety_confidence', sa.Float(), nullable=True),
    sa.Column('safety_summary', sa.Text(), nullable=True),
    sa.Column('safety_escalation_needed', sa.Boolean(), nullable=False),
    sa.Column('safety_reason_codes_json', sa.Text(), nullable=False),
    sa.Column('relationship_summary', sa.Text(), nullable=True),
    sa.Column('mood_label', sa.String(length=40), nullable=False),
    sa.Column('loneliness_signal', sa.String(length=40), nullable=False),
    sa.Column('topics_discussed_json', sa.Text(), nullable=False),
    sa.Column('follow_up_suggestions_json', sa.Text(), nullable=False),
    sa.Column('recommended_actions_json', sa.Text(), nullable=False),
    sa.Column('memory_candidates_json', sa.Text(), nullable=False),
    sa.Column('analyzer', sa.String(length=80), nullable=False),
    sa.Column('raw_analysis_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['check_in_call_sessions.id'], ),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_ins.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_insights_call_session_id'), 'conversation_insights', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_conversation_insights_check_in_id'), 'conversation_insights', ['check_in_id'], unique=False)
    op.create_index(op.f('ix_conversation_insights_id'), 'conversation_insights', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_insights_safety_risk_level'), 'conversation_insights', ['safety_risk_level'], unique=False)
    op.create_index(op.f('ix_conversation_insights_senior_call_sid'), 'conversation_insights', ['senior_call_sid'], unique=False)
    op.create_index(op.f('ix_conversation_insights_senior_id'), 'conversation_insights', ['senior_id'], unique=False)
    op.create_table('transcript_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('check_in_id', sa.Integer(), nullable=True),
    sa.Column('call_session_id', sa.Integer(), nullable=True),
    sa.Column('senior_call_sid', sa.String(length=80), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('started_at_ms', sa.Integer(), nullable=True),
    sa.Column('ended_at_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['check_in_call_sessions.id'], ),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_ins.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_turns_call_session_id'), 'transcript_turns', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_transcript_turns_check_in_id'), 'transcript_turns', ['check_in_id'], unique=False)
    op.create_index(op.f('ix_transcript_turns_id'), 'transcript_turns', ['id'], unique=False)
    op.create_index(op.f('ix_transcript_turns_senior_call_sid'), 'transcript_turns', ['senior_call_sid'], unique=False)
    op.create_index(op.f('ix_transcript_turns_senior_id'), 'transcript_turns', ['senior_id'], unique=False)
    op.create_table('operator_action_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_action_id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('check_in_id', sa.Integer(), nullable=False),
    sa.Column('conversation_insight_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_ins.id'], ),
    sa.ForeignKeyConstraint(['conversation_insight_id'], ['conversation_insights.id'], ),
    sa.ForeignKeyConstraint(['operator_action_id'], ['operator_actions.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_action_id', 'check_in_id', name='uq_operator_action_evidence_action_checkin')
    )
    op.create_index(op.f('ix_operator_action_evidence_check_in_id'), 'operator_action_evidence', ['check_in_id'], unique=False)
    op.create_index(op.f('ix_operator_action_evidence_conversation_insight_id'), 'operator_action_evidence', ['conversation_insight_id'], unique=False)
    op.create_index(op.f('ix_operator_action_evidence_id'), 'operator_action_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_operator_action_evidence_operator_action_id'), 'operator_action_evidence', ['operator_action_id'], unique=False)
    op.create_index(op.f('ix_operator_action_evidence_senior_id'), 'operator_action_evidence', ['senior_id'], unique=False)
    op.create_table('senior_memory_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('check_in_id', sa.Integer(), nullable=True),
    sa.Column('insight_id', sa.Integer(), nullable=True),
    sa.Column('memory_type', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_ins.id'], ),
    sa.ForeignKeyConstraint(['insight_id'], ['conversation_insights.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_senior_memory_candidates_check_in_id'), 'senior_memory_candidates', ['check_in_id'], unique=False)
    op.create_index(op.f('ix_senior_memory_candidates_id'), 'senior_memory_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_senior_memory_candidates_insight_id'), 'senior_memory_candidates', ['insight_id'], unique=False)
    op.create_index(op.f('ix_senior_memory_candidates_senior_id'), 'senior_memory_candidates', ['senior_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_senior_memory_candidates_senior_id'), table_name='senior_memory_candidates')
    op.drop_index(op.f('ix_senior_memory_candidates_insight_id'), table_name='senior_memory_candidates')
    op.drop_index(op.f('ix_senior_memory_candidates_id'), table_name='senior_memory_candidates')
    op.drop_index(op.f('ix_senior_memory_candidates_check_in_id'), table_name='senior_memory_candidates')
    op.drop_table('senior_memory_candidates')
    op.drop_index(op.f('ix_operator_action_evidence_senior_id'), table_name='operator_action_evidence')
    op.drop_index(op.f('ix_operator_action_evidence_operator_action_id'), table_name='operator_action_evidence')
    op.drop_index(op.f('ix_operator_action_evidence_id'), table_name='operator_action_evidence')
    op.drop_index(op.f('ix_operator_action_evidence_conversation_insight_id'), table_name='operator_action_evidence')
    op.drop_index(op.f('ix_operator_action_evidence_check_in_id'), table_name='operator_action_evidence')
    op.drop_table('operator_action_evidence')
    op.drop_index(op.f('ix_transcript_turns_senior_id'), table_name='transcript_turns')
    op.drop_index(op.f('ix_transcript_turns_senior_call_sid'), table_name='transcript_turns')
    op.drop_index(op.f('ix_transcript_turns_id'), table_name='transcript_turns')
    op.drop_index(op.f('ix_transcript_turns_check_in_id'), table_name='transcript_turns')
    op.drop_index(op.f('ix_transcript_turns_call_session_id'), table_name='transcript_turns')
    op.drop_table('transcript_turns')
    op.drop_index(op.f('ix_conversation_insights_senior_id'), table_name='conversation_insights')
    op.drop_index(op.f('ix_conversation_insights_senior_call_sid'), table_name='conversation_insights')
    op.drop_index(op.f('ix_conversation_insights_safety_risk_level'), table_name='conversation_insights')
    op.drop_index(op.f('ix_conversation_insights_id'), table_name='conversation_insights')
    op.drop_index(op.f('ix_conversation_insights_check_in_id'), table_name='conversation_insights')
    op.drop_index(op.f('ix_conversation_insights_call_session_id'), table_name='conversation_insights')
    op.drop_table('conversation_insights')
    op.drop_index(op.f('ix_operator_actions_target_contact_id'), table_name='operator_actions')
    op.drop_index(op.f('ix_operator_actions_status'), table_name='operator_actions')
    op.drop_index(op.f('ix_operator_actions_senior_id'), table_name='operator_actions')
    op.drop_index(op.f('ix_operator_actions_id'), table_name='operator_actions')
    op.drop_index(op.f('ix_operator_actions_action_type'), table_name='operator_actions')
    op.drop_table('operator_actions')
    op.drop_index(op.f('ix_escalation_steps_target_contact_id'), table_name='escalation_steps')
    op.drop_index(op.f('ix_escalation_steps_plan_id'), table_name='escalation_steps')
    op.drop_index(op.f('ix_escalation_steps_id'), table_name='escalation_steps')
    op.drop_table('escalation_steps')
    op.drop_index(op.f('ix_check_in_call_sessions_senior_id'), table_name='check_in_call_sessions')
    op.drop_index(op.f('ix_check_in_call_sessions_senior_call_sid'), table_name='check_in_call_sessions')
    op.drop_index(op.f('ix_check_in_call_sessions_id'), table_name='check_in_call_sessions')
    op.drop_index(op.f('ix_check_in_call_sessions_caregiver_id'), table_name='check_in_call_sessions')
    op.drop_table('check_in_call_sessions')
    op.drop_index(op.f('ix_voice_baseline_samples_senior_id'), table_name='voice_baseline_samples')
    op.drop_index(op.f('ix_voice_baseline_samples_id'), table_name='voice_baseline_samples')
    op.drop_index(op.f('ix_voice_baseline_samples_baseline_call_sid'), table_name='voice_baseline_samples')
    op.drop_table('voice_baseline_samples')
    op.drop_index(op.f('ix_voice_baseline_comparisons_senior_id'), table_name='voice_baseline_comparisons')
    op.drop_index(op.f('ix_voice_baseline_comparisons_senior_call_sid'), table_name='voice_baseline_comparisons')
    op.drop_index(op.f('ix_voice_baseline_comparisons_id'), table_name='voice_baseline_comparisons')
    op.drop_index(op.f('ix_voice_baseline_comparisons_check_in_id'), table_name='voice_baseline_comparisons')
    op.drop_index(op.f('ix_voice_baseline_comparisons_baseline_sample_id'), table_name='voice_baseline_comparisons')
    op.drop_index(op.f('ix_voice_baseline_comparisons_baseline_call_sid'), table_name='voice_baseline_comparisons')
    op.drop_table('voice_baseline_comparisons')
    op.drop_index(op.f('ix_support_contacts_senior_id'), table_name='support_contacts')
    op.drop_index(op.f('ix_support_contacts_phone_number'), table_name='support_contacts')
    op.drop_index(op.f('ix_support_contacts_id'), table_name='support_contacts')
    op.drop_table('support_contacts')
    op.drop_index(op.f('ix_senior_heat_settings_senior_id'), table_name='senior_heat_settings')
    op.drop_index(op.f('ix_senior_heat_settings_id'), table_name='senior_heat_settings')
    op.drop_table('senior_heat_settings')
    op.drop_index(op.f('ix_senior_demographics_senior_id'), table_name='senior_demographics')
    op.drop_index(op.f('ix_senior_demographics_id'), table_name='senior_demographics')
    op.drop_table('senior_demographics')
    op.drop_index(op.f('ix_escalation_plans_senior_id'), table_name='escalation_plans')
    op.drop_index(op.f('ix_escalation_plans_id'), table_name='escalation_plans')
    op.drop_table('escalation_plans')
    op.drop_index(op.f('ix_check_in_schedules_senior_id'), table_name='check_in_schedules')
    op.drop_index(op.f('ix_check_in_schedules_id'), table_name='check_in_schedules')
    op.drop_table('check_in_schedules')
    op.drop_index(op.f('ix_caregiver_profiles_senior_id'), table_name='caregiver_profiles')
    op.drop_index(op.f('ix_caregiver_profiles_phone_number'), table_name='caregiver_profiles')
    op.drop_index(op.f('ix_caregiver_profiles_id'), table_name='caregiver_profiles')
    op.drop_table('caregiver_profiles')
    op.drop_index(op.f('ix_senior_profiles_phone_number'), table_name='senior_profiles')
    op.drop_index(op.f('ix_senior_profiles_id'), table_name='senior_profiles')
    op.drop_table('senior_profiles')
    op.drop_index(op.f('ix_heat_triggered_calls_senior_id'), table_name='heat_triggered_calls')
    op.drop_index(op.f('ix_heat_triggered_calls_senior_call_sid'), table_name='heat_triggered_calls')
    op.drop_index(op.f('ix_heat_triggered_calls_local_date'), table_name='heat_triggered_calls')
    op.drop_index(op.f('ix_heat_triggered_calls_id'), table_name='heat_triggered_calls')
    op.drop_table('heat_triggered_calls')
    op.drop_index(op.f('ix_heat_risk_observations_senior_id'), table_name='heat_risk_observations')
    op.drop_index(op.f('ix_heat_risk_observations_id'), table_name='heat_risk_observations')
    op.drop_index(op.f('ix_heat_risk_observations_heat_risk_value'), table_name='heat_risk_observations')
    op.drop_table('heat_risk_observations')
    op.drop_index(op.f('ix_check_ins_senior_call_sid'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_risk_level'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_caregiver_alerts_risk_level'), table_name='caregiver_alerts')
    op.drop_index(op.f('ix_caregiver_alerts_id'), table_name='caregiver_alerts')
    op.drop_index(op.f('ix_caregiver_alerts_check_in_id'), table_name='caregiver_alerts')
    op.drop_index(op.f('ix_caregiver_alerts_caregiver_call_sid'), table_name='caregiver_alerts')
    op.drop_table('caregiver_alerts')
    # ### end Alembic commands ###
