from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from app.db.database import SessionLocal, init_db
from app.db.models import CheckIn, HeatRiskObservation, SeniorHeatSettings, SeniorProfile


STATUS_PATTERN = [
    {
        "heat_risk_value": 3,
        "risk_level": "HIGH",
        "orientation_concern": False,
        "escalation_needed": True,
        "recommended_action": "Operator review + wellness check",
        "minutes_ago": 18,
    },
    {
        "heat_risk_value": 3,
        "risk_level": "MEDIUM",
        "orientation_concern": False,
        "escalation_needed": False,
        "recommended_action": "Call senior",
        "minutes_ago": 44,
    },
    {
        "heat_risk_value": 2,
        "risk_level": "LOW",
        "orientation_concern": False,
        "escalation_needed": False,
        "recommended_action": "Routine check-in",
        "minutes_ago": 120,
    },
    {
        "heat_risk_value": 1,
        "risk_level": "LOW",
        "orientation_concern": False,
        "escalation_needed": False,
        "recommended_action": "No action needed",
        "minutes_ago": 240,
    },
    {
        "heat_risk_value": 4,
        "risk_level": "HIGH",
        "orientation_concern": True,
        "escalation_needed": True,
        "recommended_action": "Escalate to operator immediately",
        "minutes_ago": 10,
    },
]


HEAT_LABELS = {
    0: "Little to no risk",
    1: "Minor",
    2: "Moderate",
    3: "Major",
    4: "Extreme",
}


def main():
    init_db()

    now = datetime.now(timezone.utc)

    with SessionLocal() as db:
        seniors = (
            db.query(SeniorProfile)
            .filter(SeniorProfile.is_active.is_(True))
            .order_by(SeniorProfile.id.asc())
            .all()
        )

        if not seniors:
            print("No seniors found. Create or seed seniors first.")
            return

        # Remove old demo operational rows to keep the script repeatable.
        db.query(CheckIn).filter(CheckIn.source == "demo_operational_status").delete()
        db.query(HeatRiskObservation).filter(HeatRiskObservation.provider == "demo").delete()

        for index, senior in enumerate(seniors):
            pattern = STATUS_PATTERN[index % len(STATUS_PATTERN)]

            heat_settings = (
                db.query(SeniorHeatSettings)
                .filter(SeniorHeatSettings.senior_id == senior.id)
                .first()
            )

            latitude = heat_settings.latitude if heat_settings else None
            longitude = heat_settings.longitude if heat_settings else None

            observed_at = now - timedelta(minutes=pattern["minutes_ago"])
            check_in_at = now - timedelta(minutes=pattern["minutes_ago"] + 5)

            db.add(
                HeatRiskObservation(
                    senior_id=senior.id,
                    provider="demo",
                    latitude=latitude,
                    longitude=longitude,
                    heat_risk_value=pattern["heat_risk_value"],
                    heat_risk_label=HEAT_LABELS[pattern["heat_risk_value"]],
                    raw_response_json="{}",
                    observed_at=observed_at,
                )
            )

            db.add(
                CheckIn(
                    source="demo_operational_status",
                    senior_phone_number=senior.phone_number,
                    twilio_phone_number="+15550000000",
                    senior_call_sid=f"DEMO-CHECKIN-{senior.id}",
                    senior_call_status="completed",
                    senior_call_duration_seconds=90,
                    transcript="Demo check-in transcript for operational status testing.",
                    speech_confidence="0.95",
                    risk_level=pattern["risk_level"],
                    reported_symptoms_json="[]",
                    red_flags_json="[]",
                    orientation_concern=pattern["orientation_concern"],
                    escalation_needed=pattern["escalation_needed"],
                    caregiver_summary="Demo operational status summary.",
                    recommended_action=pattern["recommended_action"],
                    confidence_notes="Generated by demo operational status seed.",
                    analyzer="demo",
                    raw_analysis_json="{}",
                    caregiver_alert_required=pattern["escalation_needed"],
                    caregiver_alert_sent=False,
                    created_at=check_in_at,
                    updated_at=check_in_at,
                )
            )

        db.commit()

    print("Demo operational status data seeded.")


if __name__ == "__main__":
    main()