import type {
  Senior,
  Alert,
  HeatCheck,
  ScheduleItem,
  TimelineItem,
  DashboardSummary,
  PriorityItem,
} from "./types";

export const MOCK_SENIORS: Senior[] = [
  {
    id: "eleanor-jennings",
    name: "Eleanor Jennings",
    age: 79,
    gender: "Female",
    location: "Phoenix, AZ",
    city: "Phoenix",
    state: "AZ",
    lat: 33.45,
    lng: -112.07,
    phone: "(602) 555-0198",
    address: "1/24 Desert View Dr, Phoenix, AZ 85024",
    preferredContactTime: "9:00 AM – 1:00 PM",
    medicalNotes: "Hypertension, mild COPD. Stay hydrated and sun exposure.",
    emergencyContact: "James Wilson-Said, (602) 555-7281",
    heatRisk: "High",
    status: "Urgent",
    latestCheckIn: "Today, 10:18 AM",
    assignedCaregiver: "Robert Martinez",
    recommendedAction: "Dispatch wellness check",
    isActive: true,
  },
  {
    id: "robert-martinez",
    name: "Robert Martinez",
    age: 82,
    gender: "Male",
    location: "San Antonio, TX",
    city: "San Antonio",
    state: "TX",
    lat: 29.42,
    lng: -98.49,
    phone: "(210) 555-0143",
    address: "882 River Walk Blvd, San Antonio, TX 78205",
    preferredContactTime: "8:00 AM – 12:00 PM",
    medicalNotes: "Type 2 diabetes. Monitor hydration closely.",
    emergencyContact: "Maria Martinez, (210) 555-9900",
    heatRisk: "High",
    status: "Urgent",
    latestCheckIn: "Yesterday, 9:45 AM",
    assignedCaregiver: "Linda Torres",
    recommendedAction: "Call senior",
    isActive: true,
  },
  {
    id: "lillian-carter",
    name: "Lillian Carter",
    age: 86,
    gender: "Female",
    location: "New Orleans, LA",
    city: "New Orleans",
    state: "LA",
    lat: 29.95,
    lng: -90.07,
    phone: "(504) 555-0267",
    address: "415 Bourbon St, New Orleans, LA 70130",
    preferredContactTime: "10:00 AM – 2:00 PM",
    medicalNotes: "Heart condition. Avoid outdoor activity above 90°F.",
    emergencyContact: "Frank Carter, (504) 555-1122",
    heatRisk: "Moderate",
    status: "Watch",
    latestCheckIn: "Today, 8:30 AM",
    assignedCaregiver: "Diane James",
    recommendedAction: "Call senior",
    isActive: true,
  },
  {
    id: "james-wilson",
    name: "James Wilson",
    age: 74,
    gender: "Male",
    location: "Miami, FL",
    city: "Miami",
    state: "FL",
    lat: 25.77,
    lng: -80.19,
    phone: "(305) 555-0384",
    address: "301 Ocean Dr, Miami, FL 33139",
    preferredContactTime: "7:00 AM – 11:00 AM",
    medicalNotes: "Generally healthy. Seasonal allergies.",
    emergencyContact: "Sandra Wilson, (305) 555-4455",
    heatRisk: "High",
    status: "Watch",
    latestCheckIn: "Today, 7:15 AM",
    assignedCaregiver: "Carlos Rivera",
    recommendedAction: "Routine check-in",
    isActive: true,
  },
  {
    id: "helen-brooks",
    name: "Helen Brooks",
    age: 71,
    gender: "Female",
    location: "Atlanta, GA",
    city: "Atlanta",
    state: "GA",
    lat: 33.75,
    lng: -84.39,
    phone: "(404) 555-0512",
    address: "200 Peachtree St, Atlanta, GA 30303",
    heatRisk: "Moderate",
    status: "Stable",
    latestCheckIn: "Today, 9:00 AM",
    assignedCaregiver: "Tanya Hill",
    recommendedAction: "Routine check-in",
    isActive: true,
  },
  {
    id: "george-chen",
    name: "George Chen",
    age: 77,
    gender: "Male",
    location: "Los Angeles, CA",
    city: "Los Angeles",
    state: "CA",
    lat: 34.05,
    lng: -118.24,
    phone: "(213) 555-0621",
    address: "500 Wilshire Blvd, Los Angeles, CA 90036",
    heatRisk: "Moderate",
    status: "Safe",
    latestCheckIn: "Today, 10:45 AM",
    assignedCaregiver: "Amy Park",
    recommendedAction: "No action needed",
    isActive: true,
  },
  {
    id: "dorothy-hayes",
    name: "Dorothy Hayes",
    age: 83,
    gender: "Female",
    location: "Denver, CO",
    city: "Denver",
    state: "CO",
    lat: 39.74,
    lng: -104.99,
    phone: "(720) 555-0733",
    address: "1400 16th St, Denver, CO 80202",
    heatRisk: "Low",
    status: "Safe",
    latestCheckIn: "Today, 11:20 AM",
    assignedCaregiver: "Paul Henderson",
    recommendedAction: "No action needed",
    isActive: true,
  },
  {
    id: "william-thomas",
    name: "William Thomas",
    age: 78,
    gender: "Male",
    location: "Chicago, IL",
    city: "Chicago",
    state: "IL",
    lat: 41.85,
    lng: -87.63,
    phone: "(312) 555-0845",
    address: "233 S Wacker Dr, Chicago, IL 60606",
    heatRisk: "Low",
    status: "Stable",
    latestCheckIn: "Today, 8:55 AM",
    assignedCaregiver: "Rosa Kim",
    recommendedAction: "No action needed",
    isActive: true,
  },
  {
    id: "mary-johnson",
    name: "Mary Johnson",
    age: 80,
    gender: "Female",
    location: "Seattle, WA",
    city: "Seattle",
    state: "WA",
    lat: 47.61,
    lng: -122.33,
    phone: "(206) 555-0962",
    address: "Pike Place Market, Seattle, WA 98101",
    heatRisk: "Low",
    status: "Safe",
    latestCheckIn: "Today, 9:30 AM",
    assignedCaregiver: "Tom Davis",
    recommendedAction: "No action needed",
    isActive: true,
  },
  {
    id: "frank-nguyen",
    name: "Frank Nguyen",
    age: 75,
    gender: "Male",
    location: "Houston, TX",
    city: "Houston",
    state: "TX",
    lat: 29.76,
    lng: -95.37,
    phone: "(713) 555-1074",
    address: "1001 Main St, Houston, TX 77002",
    heatRisk: "High",
    status: "Watch",
    latestCheckIn: "Yesterday, 4:00 PM",
    assignedCaregiver: "Nancy Patel",
    recommendedAction: "Call senior",
    isActive: true,
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "a1",
    seniorId: "eleanor-jennings",
    seniorName: "Eleanor Jennings",
    seniorAge: 79,
    location: "Phoenix, AZ",
    type: "Extreme heat risk",
    severity: "High",
    message: "Eleanor has not confirmed hydration in over 4 hours. Wellness check recommended.",
    time: "10:18 AM",
    acknowledged: false,
  },
  {
    id: "a2",
    seniorId: "robert-martinez",
    seniorName: "Robert Martinez",
    seniorAge: 82,
    location: "San Antonio, TX",
    type: "Missed check-in",
    severity: "High",
    message: "Robert missed his scheduled 9 AM check-in. No contact established.",
    time: "9:15 AM",
    acknowledged: false,
  },
  {
    id: "a3",
    seniorId: "lillian-carter",
    seniorName: "Lillian Carter",
    seniorAge: 86,
    location: "New Orleans, LA",
    type: "Wellness check needed",
    severity: "Moderate",
    message: "Lillian reported feeling unwell during morning check-in.",
    time: "8:30 AM",
    acknowledged: false,
  },
  {
    id: "a4",
    seniorId: "frank-nguyen",
    seniorName: "Frank Nguyen",
    seniorAge: 75,
    location: "Houston, TX",
    type: "No response",
    severity: "High",
    message: "Frank has not responded to three call attempts.",
    time: "Yesterday, 4:45 PM",
    acknowledged: true,
  },
];

export const MOCK_HEAT_CHECK: HeatCheck = {
  id: "live-eleanor",
  seniorId: "eleanor-jennings",
  seniorName: "Eleanor Jennings",
  phone: "(602) 555-0198",
  location: "Phoenix, AZ",
  callDuration: "02:47",
  status: "active",
  transcript: [
    {
      speaker: "Agent",
      name: "Agent",
      text: "Hi Eleanor, this is Sarah with the Phoenix Heat Check team. How are you feeling today?",
      time: "10:16 AM",
    },
    {
      speaker: "Senior",
      name: "Eleanor Jennings",
      text: "I'm feeling okay... a little tired, you know. It's been so hot.",
      time: "10:16 AM",
    },
    {
      speaker: "Agent",
      name: "Agent",
      text: "Have you had something to drink today? Any water?",
      time: "10:17 AM",
    },
    {
      speaker: "Senior",
      name: "Eleanor Jennings",
      text: "Not much, just coffee this morning.",
      time: "10:17 AM",
    },
  ],
  riskSummary: {
    hydrationConcern: "Elevated",
    confusionIndicator: "Low",
    currentHeatRisk: "High",
    score: 8.2,
  },
  recommendedAction: "Dispatch wellness check",
  weather: "104°F Sunny",
  lastCheckIn: "Today, 10:18 AM",
};

export const MOCK_SCHEDULE: ScheduleItem[] = [
  {
    time: "9:30 AM",
    type: "Check-in Call",
    seniorName: "Robert Martinez, 82",
    location: "San Antonio, TX",
  },
  {
    time: "10:30 AM",
    type: "Check-in Call",
    seniorName: "Lillian Carter, 86",
    location: "New Orleans, LA",
  },
  {
    time: "1:00 PM",
    type: "Wellness Visit",
    seniorName: "James Wilson, 74",
    location: "Miami, FL",
  },
];

export const MOCK_PRIORITIES: PriorityItem[] = [
  {
    rank: 1,
    seniorId: "eleanor-jennings",
    seniorName: "Eleanor Jennings",
    age: 79,
    location: "Phoenix, AZ",
    risk: "High",
    action: "Dispatch wellness check",
  },
  {
    rank: 2,
    seniorId: "robert-martinez",
    seniorName: "Robert Martinez",
    age: 82,
    location: "San Antonio, TX",
    risk: "High",
    action: "Call senior",
  },
  {
    rank: 3,
    seniorId: "lillian-carter",
    seniorName: "Lillian Carter",
    age: 86,
    location: "New Orleans, LA",
    risk: "Moderate",
    action: "Call senior",
  },
];

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  seniorsMonitored: 148,
  needOutreach: 12,
  criticalAlerts: 3,
};

export const MOCK_TIMELINE: TimelineItem[] = [
  {
    id: "t1",
    type: "check-in",
    title: "Check-in received",
    description: "Eleanor reported she is doing well.",
    time: "10:18 AM",
    date: "Today",
    status: "success",
  },
  {
    id: "t2",
    type: "call-attempt",
    title: "Call attempt",
    description: "No answer. Left voicemail.",
    time: "9:40 AM",
    date: "Today",
    status: "missed",
  },
  {
    id: "t3",
    type: "check-in",
    title: "Check-in received",
    description: "Eleanor reported staying indoors and hydrated.",
    time: "4:12 PM",
    date: "Yesterday",
    status: "success",
  },
  {
    id: "t4",
    type: "note",
    title: "Note added",
    description: "Caregiver requested grocery delivery completed.",
    time: "1:15 PM",
    date: "Yesterday",
    status: "info",
  },
  {
    id: "t5",
    type: "call-attempt",
    title: "Call attempt",
    description: "Spoke with Eleanor. She was feeling okay.",
    time: "May 27, 11:00 AM",
    date: "May 27",
    status: "success",
  },
];

export const URGENT_OUTREACH = [
  { id: "robert-martinez", name: "Robert Martinez", age: 82, location: "San Antonio, TX", status: "Urgent" as const },
  { id: "lillian-carter", name: "Lillian Carter", age: 86, location: "New Orleans, LA", status: "Urgent" as const },
  { id: "james-wilson", name: "James Wilson", age: 74, location: "Miami, FL", status: "Watch" as const },
];

export const HEAT_TREND_DATA = [
  { date: "May 21", value: 2 },
  { date: "May 22", value: 3 },
  { date: "May 23", value: 2.5 },
  { date: "May 24", value: 4 },
  { date: "May 25", value: 3 },
  { date: "May 26", value: 4.5 },
  { date: "May 27", value: 5 },
  { date: "May 28", value: 4 },
  { date: "May 29", value: 5 },
];
